#!/bin/sh

iface="wlp6s0"
essid=`iwconfig $iface | awk -F '"' '/ESSID/ {print $2}'`
signal=`iwconfig $iface | awk -F '=' '/Quality/ {print $2}' | cut -d '/' -f 1`

if [ -z "$essid" ]; then
    echo "No wifi"
else
    echo "$essid $signal%"
fi
